### ISSUE TITLE
Feedback on Sep 5 version

### ISSUE THREAD

**Issue by DanielBarstow** [windows-on-earth/winearth-webui#38]
For the movie data (for example with movie iss020-E-30460-30578

FPS should re rounded to nearest half second
Date under the movie window is wrong.  It should be the same as in the Movie Data box
F-stop - I'm not sure what [56, 10] means.  It should be something like f5.6 or f10
Change Time to Start Time
Move "full length" to come right after Start Time

In the List view, the column sequence should be Movie / Date Captured / Duration (real speed)

thank you.

**Comment by AlexNguyenJJ** [comment]
Sure, I can work on that.
Date was going to be removed since it will be shown in the Movie Data box anyways to reduce redundancy; do you still want to keep it there?
For F-stop, I'm not sure what [56,10] means either, that was just what was returned from the database as `f_number`. We were hoping you would have an idea on what that would mean.
Everything else can be done without issue

**Comment by kevincoakley** [comment]
Alex, the f-stop in f format is just the first number divided by the second number. So [56, 10] is f5.6.

**Comment by AlexNguyenJJ** [comment]
What should I do if the FPS is less than 0.5? For example, a movie has 119 images over 1770 seconds, giving it a FPS of 0.0672316384180791, with 1770 seconds as the total time for the real speed (not fast). If FPS is supposed to be for the fast version, then every movie should have 30 FPS as that is what we set it to be (correct me if I'm wrong @kevincoakley )

**Comment by AlexNguyenJJ** [comment]
Hi Dan,

I've decided to omit the FPS value from being displayed for now. With the current movies that we have, most if not all will display a FPS value of 0 and some may display 0.5. The reason I ask about the difference between the fast and real speed version FPS values is because when we speed up the time lapse image sequences to make a movie, as far as I am aware, they are all done using 30 FPS. For the original image sequences, it can vary between 1 frame per 15 seconds like you said to 1 frame every 2 seconds possibly. With a cursory look at the movies we have available to display at this moment, it seems like all the movies will have a FPS of less than 1 second for the original time lapse as there are less images than there are seconds in the returned data. We can check back on this later when we might get movies with higher FPS values
